# Generated by Django 6.0.2 on 2026-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_emailotp_email_alter_emailotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='industry_type',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='location',
            field=models.CharField(default=list, max_length=255),
        ),
    ]
