# Generated by Django 6.0.2 on 2026-03-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_postajob_industry_type_alter_postajob_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='education',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_category',
            field=models.CharField(default=list, max_length=255),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_description',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='job_highlights',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='key_skills',
            field=models.TextField(default=list),
        ),
        migrations.AlterField(
            model_name='postajob',
            name='responsibilities',
            field=models.TextField(default=list),
        ),
    ]
