# Generated by Django 6.0.2 on 2026-03-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_alter_postajob_education_alter_postajob_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postajob',
            name='department',
            field=models.CharField(default=list, max_length=255),
        ),
    ]
