# Generated by Django 6.0.2 on 2026-03-04 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Hiring in Progress', 'Hiring in Progress'), ('On Hold', 'On Hold'), ('Filled', 'Filled'), ('Closed', 'Closed')], default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='total_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employer', 'Employer'), ('jobseeker', 'Jobseeker')], max_length=10),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='Job Seeker', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_read_receipts', models.BooleanField(default=True)),
                ('restrict_duplicate_applications', models.BooleanField(default=False)),
                ('hide_cv', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
