# Generated by Django 6.0.2 on 2026-05-08 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0036_module_role_jobapplication_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notif', models.BooleanField(default=True)),
                ('inapp_notif', models.BooleanField(default=True)),
                ('sms_notif', models.BooleanField(default=False)),
                ('push_notif', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('user_mgmt', 'User Management'), ('job_mgmt', 'Job Management'), ('apps', 'Applications'), ('companies', 'Companies'), ('reports', 'Reports'), ('general', 'General')], max_length=30, unique=True)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminQuietHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='22:00')),
                ('end_time', models.TimeField(default='07:00')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('active_days', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
