# Generated by Django 6.0.5 on 2026-05-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0041_companyverification_gst_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminquiethours',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', '(UTC +05:30) Asia/Kolkata'), ('America/Los_Angeles', '(UTC -08:00) America/Los_Angeles'), ('UTC', '(UTC +00:00) UTC'), ('Europe/London', '(UTC +01:00) Europe/London'), ('Europe/Berlin', '(UTC +02:00) Europe/Berlin')], default='Asia/Kolkata', max_length=100),
        ),
    ]
