# Generated by Django 6.0.5 on 2026-05-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0043_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
