# Generated by Django 6.0.5 on 2026-05-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0047_postajob_approval_status_postajob_approved_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerPlatformSettings',
        ),
    ]
