# Generated by Django 6.0.5 on 2026-05-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0049_employerplatformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/banner/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='brand_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
