# Generated by Django 6.0.5 on 2026-05-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0051_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('job_alert', 'Job Alert'), ('application', 'Application Update'), ('system', 'System Notification'), ('complaint', 'Complaint'), ('announcement', 'Announcement')], default='system', max_length=50),
        ),
    ]
