# Generated by Django 6.0.5 on 2026-05-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0052_notification_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
