# Generated by Django 6.0.5 on 2026-05-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0057_notificationdeliverylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('phone_verification', models.BooleanField(default=False)),
                ('domain_restriction', models.BooleanField(default=False)),
                ('allowed_domains', models.JSONField(blank=True, default=['gmail.com', 'outlook.com', 'yahoo.com'])),
                ('default_role', models.CharField(default='Job Seeker', max_length=100)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Active', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('Public', 'Public'), ('Employers Only', 'Employers Only'), ('Private', 'Private')], default='Employers Only', max_length=50)),
                ('resume_visibility', models.CharField(choices=[('Public', 'Public'), ('Employers Only', 'Employers Only'), ('Private', 'Private')], default='Employers Only', max_length=50)),
                ('anonymous_profile', models.BooleanField(default=False)),
                ('profile_completion_required', models.CharField(default='0 %', max_length=20)),
                ('salary_visibility', models.BooleanField(default=True)),
                ('company_reviews', models.BooleanField(default=True)),
                ('application_status_tracking', models.BooleanField(default=True)),
                ('similar_jobs', models.BooleanField(default=True)),
                ('career_advice', models.BooleanField(default=True)),
                ('easy_apply', models.BooleanField(default=True)),
                ('save_jobs', models.BooleanField(default=True)),
                ('max_applications', models.PositiveIntegerField(default=30)),
                ('application_expiry_days', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
