# Generated by Django 6.0.5 on 2026-05-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0059_alter_jobseekerplatformsettings_allowed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
