# Generated by Django 6.0.2 on 2026-05-26 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0060_jobapplication_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='raiseticket',
            name='resolved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raiseticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Hold', 'Hold'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10-digit mobile number', regex='^\\d{10}$')]),
        ),
    ]
