# Generated by Django 6.0.2 on 2026-05-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0062_contactmessage_status_contactmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='resolved_on',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='status',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profile_photos/'),
        ),
    ]
