# Generated by Django 6.0.2 on 2026-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0065_alter_plan_options_plan_color_plan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Account_Manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='Analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='Candidate_Search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='Premium_Support',
            field=models.BooleanField(default=False),
        ),
    ]
