# Generated by Django 6.0.2 on 2026-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0034_acompany_ajobseeker_aemployer_ajob'),
    ]

    operations = [
        migrations.AddField(
            model_name='postajob',
            name='flagged',
            field=models.BooleanField(default=False, help_text='Admin flagged for review'),
        ),
    ]
