# Generated by Django 6.0.5 on 2026-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0038_smsotp_adminprofile_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_registration', models.BooleanField(default=True)),
                ('email_verification', models.BooleanField(default=True)),
                ('mobile_verification', models.BooleanField(default=False)),
                ('approval_type', models.CharField(choices=[('Manual Type', 'Manual Type'), ('Automatic', 'Automatic')], default='Manual Type', max_length=20)),
                ('req_company_cert', models.BooleanField(default=False)),
                ('req_gst_cert', models.BooleanField(default=False)),
                ('req_business_email', models.BooleanField(default=False)),
                ('req_company_website', models.BooleanField(default=False)),
                ('allow_multiple_company', models.BooleanField(default=False)),
                ('allow_multiple_users', models.BooleanField(default=False)),
                ('show_company_reviews', models.BooleanField(default=False)),
                ('enable_company_branding', models.BooleanField(default=False)),
                ('featured_employer_option', models.BooleanField(default=False)),
                ('notif_email', models.BooleanField(default=False)),
                ('notif_new_signups', models.BooleanField(default=False)),
                ('notif_alerts', models.BooleanField(default=False)),
                ('notif_announcements', models.BooleanField(default=False)),
                ('notif_weekly_summary', models.BooleanField(default=False)),
                ('default_plan', models.CharField(choices=[('Free plan', 'Free plan'), ('Premium plan', 'Premium plan'), ('Enterprise plan', 'Enterprise plan')], default='Free plan', max_length=50)),
                ('account_status', models.CharField(choices=[('Pending approval', 'Pending approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending approval', max_length=20)),
                ('job_expire_days', models.PositiveIntegerField(default=30)),
                ('max_job_posts', models.PositiveIntegerField(default=10)),
                ('featured_job_limit', models.PositiveIntegerField(default=3)),
                ('allow_edit_after_approval', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employer Platform Settings',
                'verbose_name_plural': 'Employer Platform Settings',
            },
        ),
    ]
