# Generated by Django 6.0.5 on 2026-05-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0039_employerplatformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerplatformsettings',
            name='default_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_employer_settings', to='jobapp.plan'),
        ),
    ]
