# Generated by Django 6.0.5 on 2026-05-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0040_alter_employerplatformsettings_default_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyverification',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company/gst/'),
        ),
    ]
