# Generated by Django 6.0.5 on 2026-05-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0044_companyprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='theme_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
