# Generated by Django 6.0.5 on 2026-05-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0045_companyprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='theme_color',
        ),
    ]
