# Generated by Django 6.0.5 on 2026-05-13 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0046_remove_companyprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postajob',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='postajob',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postajob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postajob',
            name='highlighted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postajob',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
