# Generated by Django 6.0.5 on 2026-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0050_companyprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('new_signup', 'New Signup'), ('alert', 'Alert'), ('announcement', 'Announcement'), ('weekly_summary', 'Weekly Summary')], max_length=50, null=True),
        ),
    ]
