# Generated by Django 6.0.5 on 2026-05-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0054_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('new_signup', 'New Signup'), ('alert', 'Alert'), ('announcement', 'Announcement'), ('weekly_summary', 'Weekly Summary'), ('application_update', 'Application Update'), ('verification', 'Verification'), ('system', 'System'), ('message', 'Message'), ('complaint', 'Complaint'), ('job_alert', 'Job Alert')], max_length=50, null=True),
        ),
    ]
