# Generated by Django 6.0.5 on 2026-05-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0055_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('user_mgmt', 'User Management'), ('job_mgmt', 'Job Management'), ('apps', 'Applications'), ('companies', 'Companies'), ('reports', 'Reports'), ('general', 'General'), ('new_signup', 'New Signup'), ('alert', 'Alert'), ('announcement', 'Announcement'), ('weekly_summary', 'Weekly Summary')], max_length=50, null=True),
        ),
    ]
