# Generated by Django 6.0.5 on 2026-05-17 03:16

import jobapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0058_jobseekerplatformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerplatformsettings',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=jobapp.models.JobseekerPlatformSettings.default_allowed_domains),
        ),
    ]
